export const availableCategories = [
	'AI Model Integration',
	'Context Management',
	'Agent Frameworks',
	'Prompt Engineering Tools',
	'Function Calling',
	'Protocol Implementations',
	'Multimodal AI',
	'AI Model Optimization',
	'Knowledge Base Systems',
	'Vector Databases',
	'Semantic Search',
	'Memory Management',
	'RAG Systems',
	'Developer Tooling',
	'API Frameworks',
	'CLI Tools',
	'Code Generation',
	'Plugin Ecosystems',
	'AI Testing Frameworks',
	'Natural Language Processing',
	'Computer Vision',
	'Speech Recognition',
	'Model Training Tools',
	'Data Processing',
	'Database Systems',
	'Storage Solutions',
	'Data Visualization',
	'ETL Pipelines',
	'Cloud Infrastructure',
	'DevOps Tools',
	'Monitoring & Observability',
	'Serverless Computing',
	'Edge Computing',
	'Real-time Systems',
	'Browser & Web Automation',
	'System Automation',
	'Workflow Orchestration',
	'Mobile Integration',
	'IoT Solutions',
	'Embedded AI',
	'Security & Privacy',
	'Identity & Access Management',
	'Compliance Solutions',
	'AI Safety',
	'Enterprise Solutions',
	'Research Tools',
	'Healthcare & Life Sciences',
	'Financial Services',
	'E-commerce Solutions',
	'Communication Platforms',
	'Content & Media',
	'Social Media Tools',
	'Translation & Localization',
];
