-- Create table for blog posts
CREATE TABLE public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    content TEXT,
    keywords TEXT[],
    slug TEXT NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'Europe/Istanbul'),
    
    -- Constraint for unique slug
    CONSTRAINT unique_blog_post_slug UNIQUE (slug)
);

-- Create index for slug (for SEO queries)
CREATE INDEX idx_blog_posts_slug ON public.blog_posts(slug);

-- Create index for creation date
CREATE INDEX idx_blog_posts_created_date ON public.blog_posts(created_date);

-- Table descriptions
COMMENT ON TABLE public.blog_posts IS 'Table storing blog posts';
COMMENT ON COLUMN public.blog_posts.id IS 'Unique post identifier';
COMMENT ON COLUMN public.blog_posts.title IS 'Post title';
COMMENT ON COLUMN public.blog_posts.description IS 'Post description';
COMMENT ON COLUMN public.blog_posts.keywords IS 'Post keywords';
COMMENT ON COLUMN public.blog_posts.created_date IS 'Post creation date';
COMMENT ON COLUMN public.blog_posts.slug IS 'Slug for SEO-friendly URL';
COMMENT ON COLUMN public.blog_posts.content IS 'Post content in markdown format';