// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {
	// Ortam değişkenleri
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	GOOGLE_GEMINI_API_KEY: string;
}
